name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r luwakx/requirements.txt

    # Create test_data directory
    - name: Create test_data directory
      run: mkdir -p test_data
          
    # Cache test data
    - name: Cache test data
      uses: actions/cache@v3
      with:
        path: test_data
        key: ${{ runner.os }}-test-data-cache
        restore-keys: |
          ${{ runner.os }}-test-data-cache

    # Download test data from the release if not cached
    - name: Download test data
      run: |
        if [ ! -f test_data/test-dicom-files-2.tar.gz ]; then
          curl -L "https://github.com/Simlomb/Test-data-anonymization/releases/download/0.0.1-dicom-files-test/test-dicom-files-2.tar.gz" \
          -o test_data/test-dicom-files-2.tar.gz && \
          tar --strip-components=1 -xvzf test_data/test-dicom-files-2.tar.gz -C test_data
        fi

    # Run tests
    - name: Run tests
      run: |
        python -m unittest discover luwakx
